server:
  port: 7002
  servlet:
    context-path: /blog
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iron_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhs
  application:
    name: iron_man_blog
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  oss-cn-beijing.aliyuncs.com
security:
  oauth2:
    client:
      client-id: blog
      client-secret:  blog
      access-token-uri: http://localhost:7800/oauth/token
      user-authorization-uri: http://localhost:7800/oauth/authorize
    resource:
      token-info-uri: http://localhost:7800/oauth/check_token