spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iron_blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: zhs
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300



#  elasticsearch:
#    jest:
#      uris: http://localhost:9200



logging:
  config: classpath:logback-spring.xml
