spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: zhs
    username: root
    url: jdbc:mysql://localhost:3306/iron_blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
# 配置日志
logging:
  level:
    root: warn
    com.zhs.plus.dao: trace

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml