server:
  port: 7000
spring:
  application:
    name: iron_man_gateway
  cloud:
    gateway:
      routes:
      - id: file #路由的ID
        uri: http://localhost:7001 #匹配后路由地址
        predicates: # 断言，路径相匹配的进行路由
          - Path=/file/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/